tabela3 = [
    ("Iene", "Rúpia", {"taxa": 5}),
    ("Iene", "Ringgit", {"taxa": 5}),
    ("Rúpia", "Iene", {"taxa": 5}),
    ("Rúpia", "Ringgit", {"taxa": 2}),
    ("Ringgit", "Iene", {"taxa": 5}),
    ("Ringgit", "Rúpia", {"taxa": 2}),
    ("Dólar americano", "Iene", {"taxa": 2}),
    ("Dólar americano", "Rúpia", {"taxa": 0.2}),
    ("Dólar americano", "Ringgit", {"taxa": 1.5}),
    ("Dólar Canadense", "Rúpia", {"taxa": 0.2}),
    ("Dólar Canadense", "Iene", {"taxa": 2}),
    ("Dólar Canadense", "Ringgit", {"taxa": 1.5}),
    ("Euro", "Rúpia", {"taxa": 1}),
    ("Euro", "Iene", {"taxa": 2}),
    ("Euro", "Ringgit", {"taxa": 2.5}),
    ("Libra", "Rúpia", {"taxa": 0.5}),
    ("Libra", "Iene", {"taxa": 2}),
    ("Libra", "Ringgit", {"taxa": 1}),
    ("Peso", "Rúpia", {"taxa": 0.2}),
    ("Peso", "Iene", {"taxa": 4}),
    ("Peso", "Ringgit", {"taxa": 1}),
]

