tabela1 = [
    # Taxas de câmbio fornecidas
    ("Iene", "Iene", {"taxa": 1}),
    ("Rúpia", "Rúpia", {"taxa": 1}),
    ("Ringgit", "Ringgit", {"taxa": 1}),
    ("Dolar canadense", "Dolar canadense", {"taxa": 1}),
    ("Dólar americano", "Dólar americano", {"taxa": 1}),
    ("Euro", "Euro", {"taxa": 1}),
    ("Libra", "Libra", {"taxa": 1}),
    ("Peso", "Peso", {"taxa": 1}),
    ("Rúpia", "Iene", {"taxa": 50}),
    ("Ringgit", "Iene", {"taxa": 0.04}),
    ("Ringgit", "Rúpia", {"taxa": 0.0008}),
    ("Dólar americano ", "Iene", {"taxa": 0.008}),
    ("Dólar americano ", "Rúpia", {"taxa": 0.00016}),
    ("Dólar americano", "Ringgit", {"taxa": 0.2}),
    ("Dólar Canadense", "Rúpia", {"taxa": 0.0002}),
    ("Dólar Canadense", "Iene", {"taxa": 0.01}),
    ("Dólar Canadense", "Ringgit", {"taxa": 0.25}),
    ("Dólar Canadense", "Dólar americano", {"taxa": 1.25}),
    ("Euro", "Rúpia", {"taxa": 0.000128}),
    ("Euro", "Iene", {"taxa": 0.0064}),
    ("Euro", "Ringgit", {"taxa": 0.16}),
    ("Euro", "Dólar americano", {"taxa": 0.8}),
    ("Euro", "Dólar Canadense", {"taxa": 0.64}),
    ("Libra", "Rúpia", {"taxa": 0.000096}),
    ("Libra", "Iene", {"taxa": 0.0048}),
    ("Libra", "Ringgit", {"taxa": 0.12}),
    ("Libra", "Dólar americano", {"taxa": 0.6}),
    ("Libra", "Dólar Canadense", {"taxa": 0.48}),
    ("Libra", "Euro", {"taxa": 0.75}),
    ("Peso", "Rúpia", {"taxa": 0.001536}),
    ("Peso", "Iene", {"taxa": 0.0768}),
    ("Peso", "Ringgit", {"taxa": 1.92}),
    ("Peso", "Dólar americano", {"taxa": 9.6}),
    ("Peso", "Dólar Canadense", {"taxa": 7.68}),
    ("Peso", "Euro", {"taxa": 12}),
    ("Peso", "Libra", {"taxa": 16}),
    
]
