tabela2 = [

    
    ("Rúpia", "Iene", {"taxa": 0.5}),
    ("Ringgit", "Iene", {"taxa": 0.5}),
    ("Ringgit", "Rúpia", {"taxa": 0.7}),
    ("Dólar americano ", "Iene", {"taxa": 0.4}),
    ("Dólar americano ", "Rúpia", {"taxa": 0.5}),
    ("Dólar americano", "Ringgit", {"taxa": 0.7}),
    ("Dólar Canadense", "Rúpia", {"taxa": 0.4}),
    ("Dólar Canadense", "Iene", {"taxa": 0.3}),
    ("Dólar Canadense", "Ringgit", {"taxa": 0.7}),
    ("Dólar Canadense", "Dólar americano", {"taxa": 0.05}),
    ("Euro", "Rúpia", {"taxa": 0.3}),
    ("Euro", "Iene", {"taxa": 0.4}),
    ("Euro", "Ringgit", {"taxa": 0.4}),
    ("Euro", "Dólar americano", {"taxa": 0.1}),
    ("Euro", "Dólar Canadense", {"taxa": 0.2}),
    ("Libra", "Rúpia", {"taxa": 0.75}),
    ("Libra", "Iene", {"taxa": 0.25}),
    ("Libra", "Ringgit", {"taxa": 0.45}),
    ("Libra", "Dólar americano", {"taxa": 0.1}),
    ("Libra", "Dólar Canadense", {"taxa": 0.1}),
    ("Libra", "Euro", {"taxa": 0.05}),
    ("Peso", "Rúpia", {"taxa": 0.5}),
    ("Peso", "Iene", {"taxa": 0.75}),
    ("Peso", "Ringgit", {"taxa": 0.5}),
    ("Peso", "Dólar americano", {"taxa": 0.1}),
    ("Peso", "Dólar Canadense", {"taxa": 0.1}),
    ("Peso", "Euro", {"taxa": 0.5}),
    ("Peso", "Libra", {"taxa": 0.5}),
    
]
